## Using API

**21.** Use a public REST API to fetch user data and display it in a structured format.

In [ ]:
import requests
import json

url = "https://randomuser.me/api/"

response = requests.get(url)
data = response.json()

user_info = data['results'][0]
name = f"{user_info['name']['title']} {user_info['name']['first']} {user_info['name']['last']}"
email = user_info['email']
phone = user_info['phone']
country = user_info['location']['country']

print(name)
print(email)
print(phone)
print(country)

Ms Buse Saygıner
buse.sayginer@example.com
(035)-164-5293
Turkey

**22.** Fetch weather information of a city using a weather API.

In [ ]:
import requests
import sys

GEO_URL = "https://geocoding-api.open-meteo.com/v1/search"
city = input("Enter the city name: ")
params = {
    "name": city,
    "language" : "en",
    "format": "json",
    "timezone": "auto"
}

response = requests.get(GEO_URL, params=params)
data = response.json()
print(data)

Enter the city name: delhi
{'results': [{'id': 1273294, 'name': 'Delhi', 'latitude': 28.65195, 'longitude': 77.23149, 'elevation': 227.0, 'feature_code': 'PPLA', 'country_code': 'IN', 'admin1_id': 1273293, 'timezone': 'Asia/Kolkata', 'population': 11034555, 'country_id': 1269750, 'country': 'India', 'admin1': 'Delhi'}, {'id': 5114824, 'name': 'Delhi', 'latitude': 42.27814, 'longitude': -74.91599, 'elevation': 418.0, 'feature_code': 'PPLA2', 'country_code': 'US', 'admin1_id': 5128638, 'admin2_id': 5114810, 'admin3_id': 5114826, 'timezone': 'America/New_York', 'population': 3157, 'postcodes': ['13753'], 'country_id': 6252001, 'country': 'United States', 'admin1': 'New York', 'admin2': 'Delaware', 'admin3': 'Town of Delhi'}, {'id': 5342522, 'name': 'Delhi', 'latitude': 37.43216, 'longitude': -120.77854, 'elevation': 36.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 5332921, 'admin2_id': 5372259, 'timezone': 'America/Los_Angeles', 'population': 10755, 'postcodes': ['95315'], 'country_id': 6252001, 'country': 'United States', 'admin1': 'California', 'admin2': 'Merced'}, {'id': 4321929, 'name': 'Delhi', 'latitude': 32.45764, 'longitude': -91.49317, 'elevation': 27.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 4331987, 'admin2_id': 4338711, 'timezone': 'America/Chicago', 'population': 2900, 'postcodes': ['71232'], 'country_id': 6252001, 'country': 'United States', 'admin1': 'Louisiana', 'admin2': 'Richland'}, {'id': 4853722, 'name': 'Delhi', 'latitude': 42.42971, 'longitude': -91.33098, 'elevation': 314.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 4862182, 'admin2_id': 4853709, 'admin3_id': 4853730, 'timezone': 'America/Chicago', 'population': 471, 'postcodes': ['52223'], 'country_id': 6252001, 'country': 'United States', 'admin1': 'Iowa', 'admin2': 'Delaware', 'admin3': 'Delhi Township'}, {'id': 5167687, 'name': 'Radnor', 'latitude': 40.38423, 'longitude': -83.15075, 'elevation': 285.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 5165418, 'admin2_id': 5151896, 'admin3_id': 5167657, 'timezone': 'America/New_York', 'population': 201, 'postcodes': ['43066'], 'country_id': 6252001, 'country': 'United States', 'admin1': 'Ohio', 'admin2': 'Delaware', 'admin3': 'Radnor Township'}, {'id': 1281378, 'name': 'Delhi', 'latitude': 37.376, 'longitude': 97.37457, 'elevation': 2991.0, 'feature_code': 'PPLA3', 'country_code': 'CN', 'admin1_id': 1280239, 'admin2_id': 1281075, 'timezone': 'Asia/Shanghai', 'country_id': 1814991, 'country': 'China', 'admin1': 'Qinghai', 'admin2': 'Haixi'}, {'id': 5024164, 'name': 'Delhi', 'latitude': 44.59913, 'longitude': -95.21111, 'elevation': 314.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 5037779, 'admin2_id': 5042847, 'admin3_id': 5024170, 'timezone': 'America/Chicago', 'population': 68, 'country_id': 6252001, 'country': 'United States', 'admin1': 'Minnesota', 'admin2': 'Redwood', 'admin3': 'City of Delhi'}, {'id': 4191253, 'name': 'Delhi', 'latitude': 33.91373, 'longitude': -82.67403, 'elevation': 159.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 4197000, 'admin2_id': 4231029, 'timezone': 'America/New_York', 'country_id': 6252001, 'country': 'United States', 'admin1': 'Georgia', 'admin2': 'Wilkes'}, {'id': 4236954, 'name': 'Delhi', 'latitude': 39.04532, 'longitude': -90.25595, 'elevation': 183.0, 'feature_code': 'PPL', 'country_code': 'US', 'admin1_id': 4896861, 'admin2_id': 4241818, 'admin3_id': 4246924, 'timezone': 'America/Chicago', 'country_id': 6252001, 'country': 'United States', 'admin1': 'Illinois', 'admin2': 'Jersey', 'admin3': 'Piasa Township'}], 'generationtime_ms': 0.85520744}

In [ ]:
url2 = "https://api.open-meteo.com/v1/forecast"
params = {
  "latitude": latitude,
  "longitude": longitude,
  "current_weather": True,
  "temperature_unit": "celsius",
  "windspeed_unit": "kmh",
    }
response = requests.get(url2, params=params, timeout=10)
data = response.json()

if "current_weather" in data:
    weather = data["current_weather"]
    print(f"Temperature: {weather['temperature']}°C")
    print(f"Wind Speed: {weather['windspeed']} km/h")
    print(f"Time: {weather['time']}")

Temperature: 20.1°C
Wind Speed: 8.7 km/h
Time: 2026-02-04T11:00

**23.** Use a JSON placeholder API to retrieve posts and store them in a JSON file.

In [ ]:
import requests
import json

n = int(input("Enter the post number: "))
url = f'https://jsonplaceholder.typicode.com/todos/{n}'
#url = 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)
data = response.json()

with open('todo.json', 'w') as f:
    json.dump(data, f, indent=4)

print("Successfully fetched data")
print(json.dumps(data, indent=4))

Enter the post number: 7
Successfully fetched data
{
    "userId": 1,
    "id": 7,
    "title": "illo expedita consequatur quia in",
    "completed": false
}

**24.** Fetch data from an API and convert the response into a CSV file.

In [ ]:
url = 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)
data = response.json()

with open('todo.csv', 'w') as f:
    f.write('userId,id,title,body\n')
    for post in data:
        f.write(f"{post['userId']},{post['id']},{post['title']},{post['body']}\n")

with open('todo.csv', 'r') as f:
  for i in range(10):
    print(f.readline())

df =  pd.DataFrame(data)
todo = df.to_csv('todo.csv')
df.head()

userId,id,title,body

1,1,sunt aut facere repellat provident occaecati excepturi optio reprehenderit,quia et suscipit

suscipit recusandae consequuntur expedita et cum

reprehenderit molestiae ut ut quas totam

nostrum rerum est autem sunt rem eveniet architecto

1,2,qui est esse,est rerum tempore vitae

sequi sint nihil reprehenderit dolor beatae ea dolores neque

fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis

qui aperiam non debitis possimus qui neque nisi nulla

1,3,ea molestias quasi exercitationem repellat qui ipsa sit aut,et iusto sed quo iure

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [ ]:
import pandas as pd

**25.** Build a simple program that consumes an API, processes the data, and displays meaningful insights (e.g., count, average, top values).

In [ ]:
url = 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)
data = response.json()

data1 =  pd.DataFrame(data)
todo = data1.to_csv('todo2.csv')

df = pd.read_csv('todo2.csv')
df.head()
drop_columns = ['userId', 'Unnamed: 0']
df.drop(drop_columns, axis=1, inplace=True)
df.head()

,id,title,body
0,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int64
 1   title   100 non-null    object
 2   body    100 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [ ]:
df.describe()

               id
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [ ]:
df['id'].value_counts()

id
1      1
2      1
3      1
4      1
5      1
      ..
96     1
97     1
98     1
99     1
100    1
Name: count, Length: 100, dtype: int64