In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Superstore.csv", encoding='Latin1')

In [ ]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

Task:
 Calculate the Year-over-Year (YoY) percentage change in total Profit for each unique Region.

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y') #format = 'mixed
df['Year'] = df['Order Date'].dt.year

In [ ]:
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
0,1,CA-2013-152156,2013-11-09,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,2013

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year'],
      dtype='object')

In [ ]:
Total_Profit = df.groupby('Region')['Profit'].sum()
Total_Profit

Region
Central     39706.3625
East        91522.7800
South       46749.4303
West       108418.4489
Name: Profit, dtype: float64

In [ ]:
YOY = df.groupby('Year')['Profit'].sum()
YOY

Year
2011    49543.9741
2012    61618.6037
2013    81726.9308
2014    93507.5131
Name: Profit, dtype: float64

In [ ]:
# total = df.groupby('Region').agg(Total_Profit=('Profit','sum'), Year=('Year','count')).sort_values(by='Total_Profit',ascending=False)
# print(total.head())

In [ ]:
pivot =  df.pivot_table(index='Region',columns="Year",values='Profit',aggfunc='sum')
pivot

Year           2011        2012        2013        2014
Region
Central    539.5534  11716.8020  19899.1629   7550.8442
East     17059.6095  21091.0130  20176.8113  33195.3462
South    11879.1200   8318.5940  17691.0192   8860.6971
West     20065.6912  20492.1947  23959.9374  43900.6256

In [ ]:
# total = df.groupby(['Region','Year'])['Profit'].sum().unstack()
# total

Titanic Dataset

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/DAV_1 assignment/Datasets/titantic.csv")
df1.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [ ]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Task:
 Determine the survival rate (as a percentage) for each combination of Passenger Class (Pclass) and Sex, and present the result in a pivoted format with Male and Female survival rates as separate columns.

In [ ]:
# survival_rates = df1.groupby(['Pclass','Sex'])['Survived'].count().unstack()
# survival_rates

In [ ]:
survival_rates = df1.groupby(['Pclass','Sex'])['Survived'].mean()*100
survival_rates

Pclass  Sex
1       female    100.0
        male        0.0
2       female    100.0
        male        0.0
3       female    100.0
        male        0.0
Name: Survived, dtype: float64

In [ ]:
# pivot1 =  df1.pivot_table(index='Pclass',columns="Sex",values='Survived',aggfunc='count',margins=True)
# pivot1

Sex     female  male  All
Pclass
1           50    57  107
2           30    63   93
3           72   146  218
All        152   266  418

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/DAV_1 assignment/Datasets/bestsellers with categories.csv",encoding='utf-8')
df2.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [ ]:
df2.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

Task:
 For each Author, find the name of their highest-rated book that also has a number of Reviews greater than the overall median number of reviews across all books.

In [ ]:
median = df2['Reviews'].median()
median

8580.0

In [ ]:
new_df = df2.where(df2['Reviews'] >= 8580)
new_df.head(7)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016.0,Non Fiction
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018.0,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017.0,Fiction
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643.0,11.0,2011.0,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735.0,30.0,2014.0,Fiction

In [ ]:
median_reviews = df2["Reviews"].median()
filtered_df = df2[df2['Reviews'] > median_reviews]
filtered_df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction

In [ ]:
Reviews = df2.groupby(['Author','Name'])['User Rating'].max()
Reviews

Author                      Name
Abraham Verghese            Cutting for Stone                                                                                                       4.6
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Classic Vines                                                                  4.4
Adam Mansbach               Go the F**k to Sleep                                                                                                    4.8
Adir Levy                   What Should Danny Do? (The Power to Choose Series)                                                                      4.8
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Your Life...And Maybe the World                                            4.7
                                                                                                                                                   ...
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, and Find Your Path Back to Health                                         4.4
William P. Young            The Shack: Where Tragedy Confronts Eternity                                                                             4.6
Wizards RPG Team            Player's Handbook (Dungeons & Dragons)                                                                                  4.8
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission System: The Divine Way to Heal You, Humanity, Mother Earth, and All…     4.6
                            Soul Healing Miracles: Ancient and New Sacred Wisdom, Knowledge, and Practical Techniques for Healing the Spiritual…    4.6
Name: User Rating, Length: 351, dtype: float64

In [ ]:
# pivot3 = df2.pivot_table(index='Author',columns="Name",values='User Rating',aggfunc='max')
# pivot3

In [ ]:
df4 =  pd.read_csv("/content/drive/MyDrive/DAV_1 assignment/Datasets/stock.csv", encoding = "Latin1")
df4.head(2)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800

In [ ]:
df4.columns
df4.shape

(1009, 8)

Task:
 Identify all trading days where the Closing Price was strictly higher than the previous trading day's price, but the Daily Trading Volume was strictly lower than the previous trading day's volume.

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1009 non-null   object
 1   Open       1009 non-null   float64
 2   High       1009 non-null   float64
 3   Low        1009 non-null   float64
 4   Close      1009 non-null   float64
 5   Adj Close  1009 non-null   float64
 6   Volume     1009 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 55.3+ KB

In [ ]:
#df4['Date'] = pd.to_datetime(df4['Date'], format='%d-%m-%Y')
df4['Date'] = pd.to_datetime(df4['Date'], format='%Y-%m-%d')
df4["Day"] = df4['Date'].dt.day #not dt.days
df4.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100,5
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800,6
2,2018-02-07,266.579987,272.450012,264.329987,264.559998,264.559998,8981500,7
3,2018-02-08,267.079987,267.619995,250.000000,250.100006,250.100006,9306700,8
4,2018-02-09,253.850006,255.800003,236.110001,249.470001,249.470001,16906900,9
5,2018-02-12,252.139999,259.149994,249.000000,257.950012,257.950012,8534900,12
6,2018-02-13,257.290009,261.410004,254.699997,258.269989,258.269989,6855200,13
7,2018-02-14,260.470001,269.880005,260.329987,266.000000,266.000000,10972000,14
8,2018-02-15,270.029999,280.500000,267.630005,280.269989,280.269989,10759700,15
9,2018-02-16,278.730011,281.959991,275.690002,278.519989,278.519989,8312400,16

Shift index by desired number of periods with an optional time freq. When freq is not passed, shift the index without realigning the data.

In [ ]:
#trading = df4.where((df4['Close'] > df4['Close']) & (df4['Volume'] < df4['Volume']))
trading = df4.where((df4['Close'] > df4['Close'].shift(1)) & (df4['Volume'] < df4['Volume'].shift(1)))
trading.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2018-02-12,252.139999,259.149994,249.000000,257.950012,257.950012,8534900.0,12.0
6,2018-02-13,257.290009,261.410004,254.699997,258.269989,258.269989,6855200.0,13.0
7,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2018-02-15,270.029999,280.500000,267.630005,280.269989,280.269989,10759700.0,15.0
9,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
trading['Day'].value_counts().sort_values(ascending=False).head()

Day
26.0    14
24.0    13
6.0     12
2.0     12
23.0    12
Name: count, dtype: int64

In [ ]:
df5 =  pd.read_csv('/content/drive/MyDrive/DAV_1 assignment/Datasets/Avocado.csv', encoding='Latin1')
df5.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year'],
      dtype='object')

Task:
 Calculate the 7-day rolling average (moving average) of the Average Price (AveragePrice) for each distinct Region and Avocado Type (e.g., 'organic', 'conventional').

#Q.6 Task:
 Find the Top 5 Host IDs (host_id) who have listings in at least 5 distinct neighborhood groups (neighbourhood_group) AND maintain an average price for all their listings of less than $150.

In [ ]:
df6 = pd.read_csv("/content/drive/MyDrive/DAV_1 assignment/Datasets/AB_NYC_2019.csv", encoding = "Latin1")
df6.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year'],
      dtype='object')

#Q.7 Task:
 Identify the workclasses that have an average hours-per-week greater than 40 AND have a total count of individuals with a marital_status of 'Never-married' less than those with 'Married-civ-spouse'.

In [ ]:
df7 = pd.read_csv("/content/drive/MyDrive/DAV_1 assignment/Datasets/adult_census.csv", encoding = "Latin1")
df7.head(2)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K

In [ ]:
df7.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [ ]:
# df_new = df7[df7['hours.per.week'] > 40]
# df_new.head(2)

In [ ]:
avg_hours = df7.groupby('workclass')['hours.per.week'].mean()
avg_hours

workclass
?                   31.919390
Federal-gov         41.379167
Local-gov           40.982800
Never-worked        28.428571
Private             40.267096
Self-emp-inc        48.818100
Self-emp-not-inc    44.421881
State-gov           39.031587
Without-pay         32.714286
Name: hours.per.week, dtype: float64

In [ ]:
df7['marital.status'].value_counts()

marital.status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [ ]:
workclass_stats = df7.groupby('workclass').agg(
    average_hours=('hours.per.week', 'mean'),
    never_married_count=('marital.status', lambda x: (x == 'Never-married').sum()),
    married_count=('marital.status', lambda x: (x == 'Married-civ-spouse').sum())
).reset_index()

workclass_stats

          workclass  average_hours  never_married_count  married_count
0                 ?      31.919390                  766            636
1       Federal-gov      41.379167                  245            471
2         Local-gov      40.982800                  530           1023
3      Never-worked      28.428571                    5              1
4           Private      40.267096                 8186           9732
5      Self-emp-inc      48.818100                  125            837
6  Self-emp-not-inc      44.421881                  409           1680
7         State-gov      39.031587                  413            588
8       Without-pay      32.714286                    4              8

In [ ]:
result = workclass_stats[
    (workclass_stats['average_hours'] > 40) &
    (workclass_stats['never_married_count'] < workclass_stats['married_count'])
]
result

          workclass  average_hours  never_married_count  married_count
1       Federal-gov      41.379167                  245            471
2         Local-gov      40.982800                  530           1023
4           Private      40.267096                 8186           9732
5      Self-emp-inc      48.818100                  125            837
6  Self-emp-not-inc      44.421881                  409           1680

In [ ]:
result['workclass'].tolist()

['Federal-gov', 'Local-gov', 'Private', 'Self-emp-inc', 'Self-emp-not-inc']

## Question 8

In [ ]:
df8 = pd.read_csv("/content/drive/MyDrive/Superstore.csv", encoding = 'Latin1')
df8.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
df8.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

Task:
 Find the Top 3 Sub-Categories (Sub-Category) that have the highest average profit per order, but restrict the analysis only to orders placed in the 'Central' region by customers in the 'Consumer' segment.

In [ ]:
df8.shape

(9994, 21)

In [ ]:
# df_new = df8.where((df8['Segment']=='Consumer') & (df8['Region']=='Central')).head(16)
df_new = df8[(df8['Segment']=='Consumer') & (df8['Region']=='Central')]
df_new.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
16,17,CA-2011-105893,11-11-2011,18-11-2011,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,53711,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.88,6,0.0,13.3176
46,47,CA-2011-146703,20-10-2011,25-10-2011,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Westland,...,48185,Central,OFF-ST-10001713,Office Supplies,Storage,"Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5...",211.96,4,0.0,8.4784

In [ ]:
# top_3 = df8.groupby('Sub-Category')['Profit'].mean()
# top_3

In [ ]:
Filter = df_new.groupby('Sub-Category').agg(Total_Profit=('Profit','sum'), order_count=('Order ID','count'))
Filter.head(2)

              Total_Profit  order_count
Sub-Category
Accessories      3743.3859          101
Appliances      -3775.6065           66

In [ ]:
Filter["avg_per_order"] = Filter["Total_Profit"]/Filter["order_count"]
Filter.head()

              Total_Profit  order_count  avg_per_order
Sub-Category
Accessories      3743.3859          101      37.063227
Appliances      -3775.6065           66     -57.206159
Art               605.5615           94       6.442144
Binders          1832.3210          193       9.493891
Bookcases       -1497.1260           24     -62.380250

In [ ]:
top3 = Filter.sort_values(by = 'avg_per_order', ascending = False)
top3[['avg_per_order']].head(3)

              avg_per_order
Sub-Category
Copiers          370.740400
Phones            61.104949
Accessories       37.063227